export const ProductsList = [
  {
    id: 1,
    productName: "Pova 5 Pro 5G ",
    imageUrl: "https://m.media-amazon.com/images/I/618akt6gi+L._AC_UY218_.jpg",
    price: "16990",
    category: "MOBILES",
    description: "thee way you selected the item is good",
  },
  {
    id: 2,
    productName: "realme narzo N55 (Prime Black, 6GB+128GB)",
    imageUrl: "https://m.media-amazon.com/images/I/81ogvU1j6qL._AC_UY218_.jpg",
    price: "14990",
    category: "MOBILES",
    description: "thee way you selected the item is good",
  },
  {
    id: 3,
    productName: "Samsung Galaxy M04 Light Green",
    imageUrl: "https://m.media-amazon.com/images/I/814ePfNubRL._AC_UY218_.jpg",
    category: "MOBILES",
    price: "11999",
    description: "thee way you selected the item is good",
  },
  {
    id: 4,
    productName: "One Plus Nord CE 2 Lite",
    imageUrl: "https://m.media-amazon.com/images/I/61K7ujVUm+L._AC_UY218_.jpg",
    category: "MOBILES",
    price: "8499",
    description: "thee way you selected the item is good",
  },
  {
    id: 5,
    productName: "Itel A60s",
    imageUrl: "https://m.media-amazon.com/images/I/71LtFZN0-7L._AC_UY218_.jpg",
    category: "MOBILES",
    price: "30000",
    description: "thee way you selected the item is good",
  },
  {
    id: 6,
    productName: "Adiyogi | Isha | Black Shiva T-Shirt",
    imageUrl: "https://m.media-amazon.com/images/I/71xdORwbMFL._AC_UL320_.jpg",
    category: "CLOTHES",
    price: "499",
    description: "thee way you selected the item is good",
  },
  {
    id: 7,
    productName: "Regular Men's  T-Shirt",
    imageUrl: "https://m.media-amazon.com/images/I/51erlDVGq1L._AC_UL320_.jpg",
    category: "CLOTHES",
    price: "399",
    description: "thee way you selected the item is good",
  },
  {
    id: 8,
    productName: "Round Neck T-Shirt 2312",
    imageUrl: "https://m.media-amazon.com/images/I/71rbcoeJfwL._AC_UL320_.jpg",
    category: "CLOTHES",
    price: "599",
    description: "thee way you selected the item is good",
  },
  {
    id: 9,
    productName: "Round Neck T-Shirt 2315",
    imageUrl: "https://m.media-amazon.com/images/I/81OxGZWxrdL._AC_UL320_.jpg",
    category: "CLOTHES",
    price: "844",
    description: "thee way you selected the item is good",
  },
  {
    id: 10,
    productName: "Round Neck T-Shirt 2313",
    imageUrl: "https://m.media-amazon.com/images/I/81jJnbJfV8L._AC_UL320_.jpg",
    category: "CLOTHES",
    price: "844",
    description: "thee way you selected the item is good",
  },
  {
    id: 11,
    productName: "NIVIA Deflate Round 01 Polyester Gym Bag/Unisex Gym",
    imageUrl: "https://m.media-amazon.com/images/I/51Gszx6vb5L._AC_UL320_.jpg",
    category: "SPORTS",
    price: "770",
    description: "thee way you selected the item is good",
  },
  {
    id: 12,
    productName:
      "Lifelong PVC Hex Dumbbells Pack of 2 for Home Gym Equipment Fitness",
    imageUrl: "https://m.media-amazon.com/images/I/710SxepIfiL._AC_UL320_.jpg",
    category: "SPORTS",
    price: "350",
    description: "thee way you selected the item is good",
  },
  {
    id: 13,
    productName:
      "Amazon Brand - Symactive Neoprene Coated Solid Kettlebell for Gym",
    imageUrl: "https://m.media-amazon.com/images/I/61nASXn+LSS._AC_UL320_.jpg",
    category: "SPORTS",
    price: "1000",
    description: "thee way you selected the item is good",
  },
  {
    id: 14,
    productName: "Amazon Brand - Symactive Strength Ball 5 KG",
    imageUrl: "https://m.media-amazon.com/images/I/71tJ4YLZ2nL._AC_UL320_.jpg",
    category: "SPORTS",
    price: "800",
    description: "thee way you selected the item is good",
  },
  {
    id: 15,
    productName: "FEROC 2 Pieces Aluminium",
    imageUrl: "https://m.media-amazon.com/images/I/71Jq43IodUL._AC_UL320_.jpg",
    category: "SPORTS",
    price: "500",
    description: "thee way you selected the item is good",
  },
  {
    id: 16,
    productName: "GLUN® 50Kg Portable Scale Digital",
    imageUrl: "https://m.media-amazon.com/images/I/51d1-AL-YLL._AC_UL320_.jpg",
    category: "ELECTRONICS",
    price: "371",
    description: "thee way you selected the item is good",
  },
  {
    id: 17,
    productName: "Electronic Spices T6845-C Power",
    imageUrl: "https://m.media-amazon.com/images/I/51icSM42IIL._AC_UL320_.jpg",
    category: "ELECTRONICS",
    price: "184",
    description: "thee way you selected the item is good",
  },
  {
    id: 18,
    productName: "Electronic Spices Heavy Duty 60W/230V Soldering Iron",
    imageUrl: "https://m.media-amazon.com/images/I/61uJyaCmKDL._AC_UL320_.jpg",
    category: "ELECTRONICS",
    price: "194",
    description: "thee way you selected the item is good",
  },
  {
    id: 19,
    productName: "Sounce 7 in 1 Electronic Cleaner Kit,",
    imageUrl: "https://m.media-amazon.com/images/I/61D7N7SuqJL._AC_UL320_.jpg",
    category: "ELECTRONICS",
    price: "299",
    description: "thee way you selected the item is good",
  },
  {
    id: 20,
    productName: "STRIFF Adjustable Laptop Tabletop",
    imageUrl: "https://m.media-amazon.com/images/I/71Zf9uUp+GL._AC_UL320_.jpg",
    category: "ELECTRONICS",
    price: "349",
    description: "thee way you selected the item is good",
  },
];

// export default ProductsList;

// console.log(productsList);
